
// Interface text, English and Turkish. Widget option labels live next to the
// options in Modules.js; this file is for everything else.
var en = {
    "tour.skip": "Skip",
    "tour.back": "Back",
    "tour.next": "Next",
    "tour.done": "Start",
    "tour.keyAsk": "Add a shortcut for the editor? (SUPER + G, or the first free key like it)",
    "tour.keyTaken": "Every key it tried is already used; bind one to  dwc toggle  yourself.",
    "tour.keyAdd": "Add shortcut",
    "tour.keyOk": "Added %1 (in %2). Press it any time to open the editor.",
    "tour.keyExists": "A shortcut is already set up.",
    "tour.keyFail": "Could not add it. You can bind  dwc toggle  yourself.",
    "tour.keyNone": "No Hyprland config found; bind a key to  dwc toggle  yourself.",
    "tour.t0": "Welcome",
    "tour.p0": "Desktop Widget Control puts live widgets right on your desktop (clocks, system monitors, a music player, weather and more) and lets you arrange them yourself. This takes a minute.",
    "tour.t1": "Open the editor",
    "tour.p1": "Bind a key to  dwc toggle  and press it: your desktop turns into an editor. Esc or Done closes it again.",
    "tour.t2": "Fill the desktop",
    "tour.p2": "Drag a module from the library onto the grid, or double-click it. Widgets snap to cells and never land on top of each other; drag a corner to resize.",
    "tour.t3": "Make it yours",
    "tour.p3": "Select a widget and its panel opens: size, colours, and every option. Many modules have a Style option that swaps the whole look.",
    "tour.t4": "Pick a theme",
    "tour.p4": "Nine themes; the widgets and the editor follow the one you choose. You can change it any time in Settings.",
    "tour.t5": "You are set",
    "tour.p5": "Your layout is saved as one JSON file you can edit by hand. dwc help lists every command; dwc tour shows this again.",
    "lib.title": "Widget library",
    "lib.count": "modules",
    "lib.search": "Search…",
    "lib.all": "All",
    "lib.hint": "Drag onto the desktop, or double-click to add",
    "lib.none": "No module matches",
    "lib.full": "No room left on this screen",

    "ed.done": "Done",
    "ed.selected": "Selected",
    "ed.nothing": "Select a widget to edit it",
    "ed.nothingSub": "Click one on the desktop, or drag a new one in from the library.",
    "ed.size": "Size",
    "ed.centerH": "Centre ↔",
    "ed.centerV": "Centre ↕",
    "ed.position": "Position",
    "ed.widget": "Widget",
    "ed.style": "Appearance",
    "ed.duplicate": "Duplicate",
    "ed.delete": "Delete",
    "ed.lock": "Lock position",
    "ed.unlock": "Unlock",
    "ed.reset": "Reset to defaults",
    "ed.locked": "Locked",
    "ed.noRoom": "No room for that size here",
    "ed.keys": "Esc closes · arrows nudge · Del removes · Tab hides the panels",

    "set.title": "Settings",
    "set.theme": "Theme",
    "set.language": "Language",
    "set.langAuto": "Automatic",
    "set.cell": "Grid cell",
    "set.resetAll": "Reset layout",
    "set.resetConfirm": "Click again to reset",

    "w.noPlayer": "Nothing playing",
    "pick.anyCountry": "Any country",
    "pick.country": "Country",
    "pick.city": "City",
    "pick.search": "Type a city name…",
    "pick.searching": "Searching…",
    "pick.nothing": "No city found",
    "pick.none": "No place chosen yet",
    "w.pickCity": "Set a city",
    "w.pickCitySub": "Open the editor, select this widget and pick a country and a city",
    "w.loading": "Loading…",
    "w.offline": "Offline",
    "w.notFound": "City not found",
    "w.focus": "Focus",
    "w.break": "Break",
    "w.start": "Start",
    "w.pause": "Pause",
    "w.resume": "Resume",
    "w.reset": "Reset",
    "w.feels": "Feels like",
    "w.wind": "Wind",
    "w.swap": "Swap",
    "w.memory": "Memory",
    "w.cpu": "CPU",
    "w.down": "Down",
    "w.up": "Up",
    "w.tempNA": "No sensor",
    "w.pomoDone": "Session finished",
    "w.pomoBreakDone": "Break over",
    "w.week": "Wk",
    "w.dateLabel": "DATE",
    "w.weekLabel": "WEEK",
    "w.dayLabel": "DAY",
    "w.timeLabel": "TIME",
    "wx.clear": "Clear",
    "wx.partly": "Partly cloudy",
    "wx.cloudy": "Cloudy",
    "wx.fog": "Fog",
    "wx.drizzle": "Drizzle",
    "wx.rain": "Rain",
    "wx.showers": "Showers",
    "wx.snow": "Snow",
    "wx.storm": "Thunderstorm"
};

var tr = {
    "tour.skip": "Atla",
    "tour.back": "Geri",
    "tour.next": "İleri",
    "tour.done": "Başla",
    "tour.keyAsk": "Düzenleyici için kısayol eklensin mi? (SUPER + G, doluysa ilk boş benzeri)",
    "tour.keyTaken": "Denenen her tuş zaten kullanılıyor; bir tuşu  dwc toggle  komutuna kendin bağla.",
    "tour.keyAdd": "Kısayolu ekle",
    "tour.keyOk": "%1 eklendi (%2 içine). İstediğin zaman basıp düzenleyiciyi aç.",
    "tour.keyExists": "Bir kısayol zaten ayarlı.",
    "tour.keyFail": "Eklenemedi. İstersen  dwc toggle  komutuna kendin bir tuş bağla.",
    "tour.keyNone": "Hyprland yapılandırması bulunamadı; bir tuşu  dwc toggle  komutuna kendin bağla.",
    "tour.t0": "Hoş geldin",
    "tour.p0": "Desktop Widget Control canlı widget'ları (saatler, sistem monitörleri, müzik oynatıcı, hava durumu ve dahası) doğrudan masaüstüne koyar ve düzenini senin belirlemene izin verir. Bir dakika sürer.",
    "tour.t1": "Düzenleyiciyi aç",
    "tour.p1": "Bir tuşu  dwc toggle  komutuna bağla ve bas: masaüstün düzenleyiciye dönüşür. Esc ya da Bitti kapatır.",
    "tour.t2": "Masaüstünü doldur",
    "tour.p2": "Kütüphaneden bir modülü ızgaraya sürükle ya da çift tıkla. Widget'lar hücrelere yapışır, üst üste binmez; köşeden sürükleyerek boyutlandırırsın.",
    "tour.t3": "Sana göre yap",
    "tour.p3": "Bir widget'ı seç, paneli açılır: boyut, renkler ve bütün seçenekler. Birçok modülde tüm görünümü değiştiren bir Stil seçeneği var.",
    "tour.t4": "Bir tema seç",
    "tour.p4": "Dokuz tema; widget'lar ve düzenleyici seçtiğin temayı izler. İstediğin zaman Ayarlar'dan değiştirebilirsin.",
    "tour.t5": "Hazırsın",
    "tour.p5": "Düzenin elle değiştirebileceğin tek bir JSON dosyası olarak saklanır. dwc help bütün komutları listeler; dwc tour bunu yeniden gösterir.",
    "lib.title": "Widget kütüphanesi",
    "lib.count": "modül",
    "lib.search": "Ara…",
    "lib.all": "Tümü",
    "lib.hint": "Masaüstüne sürükle ya da çift tıkla",
    "lib.none": "Eşleşen modül yok",
    "lib.full": "Bu ekranda yer kalmadı",

    "ed.done": "Bitti",
    "ed.selected": "Seçili",
    "ed.nothing": "Düzenlemek için bir widget seç",
    "ed.nothingSub": "Masaüstünde birine tıkla ya da kütüphaneden yenisini sürükle.",
    "ed.size": "Boyut",
    "ed.centerH": "Yatayda ortala",
    "ed.centerV": "Dikeyde ortala",
    "ed.position": "Konum",
    "ed.widget": "Widget",
    "ed.style": "Görünüm",
    "ed.duplicate": "Kopyala",
    "ed.delete": "Sil",
    "ed.lock": "Konumu kilitle",
    "ed.unlock": "Kilidi aç",
    "ed.reset": "Varsayılana dön",
    "ed.locked": "Kilitli",
    "ed.noRoom": "Bu boyut için burada yer yok",
    "ed.keys": "Esc kapatır · oklar kaydırır · Del siler · Tab panelleri gizler",

    "set.title": "Ayarlar",
    "set.theme": "Tema",
    "set.language": "Dil",
    "set.langAuto": "Otomatik",
    "set.cell": "Izgara hücresi",
    "set.resetAll": "Düzeni sıfırla",
    "set.resetConfirm": "Sıfırlamak için tekrar tıkla",

    "w.noPlayer": "Çalan bir şey yok",
    "pick.anyCountry": "Tüm ülkeler",
    "pick.country": "Ülke",
    "pick.city": "Şehir",
    "pick.search": "Şehir adı yaz…",
    "pick.searching": "Aranıyor…",
    "pick.nothing": "Şehir bulunamadı",
    "pick.none": "Henüz yer seçilmedi",
    "w.pickCity": "Şehir seç",
    "w.pickCitySub": "Düzenleyiciyi aç, bu widget'ı seç, ülke ve şehir seç",
    "w.loading": "Yükleniyor…",
    "w.offline": "Çevrimdışı",
    "w.notFound": "Şehir bulunamadı",
    "w.focus": "Odak",
    "w.break": "Mola",
    "w.start": "Başlat",
    "w.pause": "Duraklat",
    "w.resume": "Devam",
    "w.reset": "Sıfırla",
    "w.feels": "Hissedilen",
    "w.wind": "Rüzgâr",
    "w.swap": "Swap",
    "w.memory": "Bellek",
    "w.cpu": "CPU",
    "w.down": "İndirme",
    "w.up": "Yükleme",
    "w.tempNA": "Sensör yok",
    "w.pomoDone": "Oturum bitti",
    "w.pomoBreakDone": "Mola bitti",
    "w.week": "Hf",
    "w.dateLabel": "TARİH",
    "w.weekLabel": "HAFTA",
    "w.dayLabel": "GÜN",
    "w.timeLabel": "SAAT",
    "wx.clear": "Açık",
    "wx.partly": "Parçalı bulutlu",
    "wx.cloudy": "Bulutlu",
    "wx.fog": "Sisli",
    "wx.drizzle": "Çise",
    "wx.rain": "Yağmurlu",
    "wx.showers": "Sağanak",
    "wx.snow": "Karlı",
    "wx.storm": "Gök gürültülü"
};

var tables = { en: en, tr: tr };

function t(lang, key) {
    var tbl = tables[lang] || en;
    if (tbl[key] !== undefined)
        return tbl[key];
    return en[key] !== undefined ? en[key] : key;
}

// Language codes the settings offer, besides "auto".
var languages = [
    { v: "en", label: "English" },
    { v: "tr", label: "Türkçe" }
];
